---
- name: Set up separate drive for IT group on server2
  hosts: server2
  become: yes
  tasks:

    - name: Create GPT partition table
      shell: |
        parted /dev/nvme1n1 mklabel gpt
      args:
        creates: /dev/nvme1n1

    - name: Create primary partition with specified size
      shell: |
        echo -e "n\np\n1\n\n+1G\nw" | fdisk /dev/nvme1n1
      args:
        creates: /dev/nvme1n1p1

    - name: Ensure the partition is aligned optimally
      shell: |
        partprobe /dev/nvme1n1

    - name: Format the partition with XFS filesystem
      filesystem:
        fstype: xfs
        dev: /dev/nvme1n1p1

    - name: Create the mount point directory /extdrive
      file:
        path: /extdrive
        state: directory
        mode: '0750'

    - name: Add the partition to /etc/fstab for auto-mounting
      mount:
        path: /extdrive
        src: /dev/nvme1n1p1
        fstype: xfs
        opts: defaults
        state: mounted
