---
- name: Set up separate drive for IT group on server2
  hosts: server2
  become: yes
  tasks:

    - name: Create a 1GB partition on /dev/nvme1n1
      parted:
        device: /dev/nvme1n1
        label: gpt
        number: 1
        size: 1GB
        state: present
        part_type: primary
        align: optimal

    - name: Format the partition with XFS filesystem
      filesystem:
        fstype: xfs
        dev: /dev/nvme1n1p1

    - name: Create the mount point directory /extdrive
      file:
        path: /extdrive
        state: directory
        mode: '0750'

    - name: Add the partition to /etc/fstab for auto-mounting
      mount:
        path: /extdrive
        src: /dev/nvme1n1p1
        fstype: xfs
        opts: defaults
        state: mounted
